// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: proto/bidirectStreamService/bidirectStreamService.proto

package bidirectStreamService

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bidirectStreamService_bidirectStreamService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bidirectStreamService_bidirectStreamService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_bidirectStreamService_bidirectStreamService_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bidirectStreamService_bidirectStreamService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bidirectStreamService_bidirectStreamService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_bidirectStreamService_bidirectStreamService_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_proto_bidirectStreamService_bidirectStreamService_proto protoreflect.FileDescriptor

var file_proto_bidirectStreamService_bidirectStreamService_proto_rawDesc = []byte{
	0x0a, 0x37, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x69,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x39, 0x0a, 0x0e, 0x42, 0x69, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x27, 0x0a, 0x0c, 0x44, 0x61,
	0x74, 0x61, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x08, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28,
	0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bidirectStreamService_bidirectStreamService_proto_rawDescOnce sync.Once
	file_proto_bidirectStreamService_bidirectStreamService_proto_rawDescData = file_proto_bidirectStreamService_bidirectStreamService_proto_rawDesc
)

func file_proto_bidirectStreamService_bidirectStreamService_proto_rawDescGZIP() []byte {
	file_proto_bidirectStreamService_bidirectStreamService_proto_rawDescOnce.Do(func() {
		file_proto_bidirectStreamService_bidirectStreamService_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bidirectStreamService_bidirectStreamService_proto_rawDescData)
	})
	return file_proto_bidirectStreamService_bidirectStreamService_proto_rawDescData
}

var file_proto_bidirectStreamService_bidirectStreamService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bidirectStreamService_bidirectStreamService_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: Request
	(*Response)(nil), // 1: Response
}
var file_proto_bidirectStreamService_bidirectStreamService_proto_depIdxs = []int32{
	0, // 0: BidirectStream.DataExchange:input_type -> Request
	1, // 1: BidirectStream.DataExchange:output_type -> Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bidirectStreamService_bidirectStreamService_proto_init() }
func file_proto_bidirectStreamService_bidirectStreamService_proto_init() {
	if File_proto_bidirectStreamService_bidirectStreamService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bidirectStreamService_bidirectStreamService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bidirectStreamService_bidirectStreamService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bidirectStreamService_bidirectStreamService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bidirectStreamService_bidirectStreamService_proto_goTypes,
		DependencyIndexes: file_proto_bidirectStreamService_bidirectStreamService_proto_depIdxs,
		MessageInfos:      file_proto_bidirectStreamService_bidirectStreamService_proto_msgTypes,
	}.Build()
	File_proto_bidirectStreamService_bidirectStreamService_proto = out.File
	file_proto_bidirectStreamService_bidirectStreamService_proto_rawDesc = nil
	file_proto_bidirectStreamService_bidirectStreamService_proto_goTypes = nil
	file_proto_bidirectStreamService_bidirectStreamService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BidirectStreamClient is the client API for BidirectStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BidirectStreamClient interface {
	DataExchange(ctx context.Context, opts ...grpc.CallOption) (BidirectStream_DataExchangeClient, error)
}

type bidirectStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewBidirectStreamClient(cc grpc.ClientConnInterface) BidirectStreamClient {
	return &bidirectStreamClient{cc}
}

func (c *bidirectStreamClient) DataExchange(ctx context.Context, opts ...grpc.CallOption) (BidirectStream_DataExchangeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BidirectStream_serviceDesc.Streams[0], "/BidirectStream/DataExchange", opts...)
	if err != nil {
		return nil, err
	}
	x := &bidirectStreamDataExchangeClient{stream}
	return x, nil
}

type BidirectStream_DataExchangeClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type bidirectStreamDataExchangeClient struct {
	grpc.ClientStream
}

func (x *bidirectStreamDataExchangeClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bidirectStreamDataExchangeClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BidirectStreamServer is the server API for BidirectStream service.
type BidirectStreamServer interface {
	DataExchange(BidirectStream_DataExchangeServer) error
}

// UnimplementedBidirectStreamServer can be embedded to have forward compatible implementations.
type UnimplementedBidirectStreamServer struct {
}

func (*UnimplementedBidirectStreamServer) DataExchange(BidirectStream_DataExchangeServer) error {
	return status.Errorf(codes.Unimplemented, "method DataExchange not implemented")
}

func RegisterBidirectStreamServer(s *grpc.Server, srv BidirectStreamServer) {
	s.RegisterService(&_BidirectStream_serviceDesc, srv)
}

func _BidirectStream_DataExchange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BidirectStreamServer).DataExchange(&bidirectStreamDataExchangeServer{stream})
}

type BidirectStream_DataExchangeServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type bidirectStreamDataExchangeServer struct {
	grpc.ServerStream
}

func (x *bidirectStreamDataExchangeServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bidirectStreamDataExchangeServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BidirectStream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BidirectStream",
	HandlerType: (*BidirectStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DataExchange",
			Handler:       _BidirectStream_DataExchange_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/bidirectStreamService/bidirectStreamService.proto",
}
